# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user1',
            name='place',
        ),
        migrations.AddField(
            model_name='user1',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user1',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
